openapi: 3.0.3
info:
  title: Liminal Type Chat Edge API
  description: |
    Edge API for Liminal Type Chat application.
    This API is optimized for frontend UI consumption and provides an interface
    for managing conversations and messages.
  version: 1.0.0
  contact:
    name: Liminal Type Chat Team
servers:
  - url: http://localhost:8765
    description: Local development server
paths:
  /api/v1/conversations:
    get:
      summary: Get all conversations
      description: Retrieve a list of conversation summaries
      operationId: getConversations
      tags:
        - Conversations
      parameters:
        - name: limit
          in: query
          description: Maximum number of conversations to return
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Number of conversations to skip
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new conversation
      description: Create a new conversation with an optional title and initial message
      operationId: createConversation
      tags:
        - Conversations
      requestBody:
        description: Conversation to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConversationRequest'
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/conversations/{conversationId}:
    get:
      summary: Get a conversation by ID
      description: Retrieve a single conversation by its ID
      operationId: getConversationById
      tags:
        - Conversations
      parameters:
        - name: conversationId
          in: path
          description: ID of the conversation to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update a conversation
      description: Update an existing conversation's properties (e.g., title)
      operationId: updateConversation
      tags:
        - Conversations
      parameters:
        - name: conversationId
          in: path
          description: ID of the conversation to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Properties to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConversationRequest'
      responses:
        '200':
          description: Conversation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a conversation
      description: Delete a conversation by its ID
      operationId: deleteConversation
      tags:
        - Conversations
      parameters:
        - name: conversationId
          in: path
          description: ID of the conversation to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Conversation deleted
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/conversations/{conversationId}/messages:
    post:
      summary: Add a message to a conversation
      description: Add a new message to an existing conversation
      operationId: addMessage
      tags:
        - Messages
      parameters:
        - name: conversationId
          in: path
          description: ID of the conversation to add the message to
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Message to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMessageRequest'
      responses:
        '201':
          description: Message added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health:
    get:
      summary: Health check
      description: Check if the server is running
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  version:
                    type: string
                    example: 1.0.0
                  timestamp:
                    type: string
                    format: date-time
components:
  schemas:
    ConversationResponse:
      type: object
      required:
        - conversationId
        - createdAt
        - updatedAt
        - messages
      properties:
        conversationId:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        title:
          type: string
          nullable: true
          description: Title of the conversation
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp of conversation creation
        updatedAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp of last conversation update
        messages:
          type: array
          description: Array of messages in the conversation
          items:
            $ref: '#/components/schemas/MessageResponse'
        metadata:
          type: object
          description: Optional key-value pairs of metadata
          additionalProperties: true
    MessageResponse:
      type: object
      required:
        - messageId
        - role
        - content
        - createdAt
      properties:
        messageId:
          type: string
          format: uuid
          description: Unique identifier for the message
        role:
          type: string
          enum:
            - user
            - assistant
            - system
            - tool
          description: Role of the message sender
        content:
          type: string
          description: Text content of the message
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp of message creation
        status:
          type: string
          enum:
            - pending
            - streaming
            - complete
            - error
            - interrupted
          description: Status of the message processing
        metadata:
          type: object
          description: Optional key-value pairs of metadata
          additionalProperties: true
    CreateConversationRequest:
      type: object
      properties:
        title:
          type: string
          nullable: true
          description: Optional title for the conversation
        initialMessage:
          type: object
          description: Optional initial message to start the conversation
          required:
            - role
            - content
          properties:
            role:
              type: string
              enum:
                - user
                - assistant
                - system
                - tool
              description: Role of the message sender
            content:
              type: string
              description: Text content of the message
            metadata:
              type: object
              description: Optional key-value pairs of metadata
              additionalProperties: true
        metadata:
          type: object
          description: Optional key-value pairs of metadata
          additionalProperties: true
    UpdateConversationRequest:
      type: object
      properties:
        title:
          type: string
          nullable: true
          description: New title for the conversation. Send null to clear the title.
        metadata:
          type: object
          description: Optional key-value pairs of metadata to update
          additionalProperties: true
    AddMessageRequest:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum:
            - user
            - assistant
            - system
            - tool
          description: Role of the message sender
        content:
          type: string
          description: Text content of the message
        status:
          type: string
          enum:
            - pending
            - streaming
            - complete
            - error
            - interrupted
          description: Optional initial status of the message
        metadata:
          type: object
          description: Optional key-value pairs of metadata
          additionalProperties: true
    ConversationListResponse:
      type: object
      required:
        - conversations
      properties:
        conversations:
          type: array
          description: Array of conversation summaries
          items:
            $ref: '#/components/schemas/ConversationSummary'
    ConversationSummary:
      type: object
      required:
        - conversationId
        - createdAt
        - updatedAt
      properties:
        conversationId:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        title:
          type: string
          nullable: true
          description: Title of the conversation
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp of conversation creation
        updatedAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp of last conversation update
        metadata:
          type: object
          description: Optional key-value pairs of metadata
          additionalProperties: true
    ErrorResponse:
      type: object
      required:
        - errorCode
        - message
      properties:
        errorCode:
          type: string
          description: Error code identifying the type of error
          example: VALIDATION_ERROR
        message:
          type: string
          description: User-friendly error message
          example: Invalid request data
        details:
          type: string
          nullable: true
          description: Additional details about the error
        validationErrors:
          type: array
          description: Validation errors when errorCode is VALIDATION_ERROR
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
                description: JSON path to the invalid field
                example: body.title
              message:
                type: string
                description: Description of the validation failure
                example: must be a string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authentication will be implemented in Milestone 0008"
